"""Add face_registered_at column to users table

Revision ID: 0a2f2b7a196f
Revises: f2166171c6a5
Create Date: 2025-10-23 10:39:04.626531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2f2b7a196f'
down_revision = 'f2166171c6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_registered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('face_registered_at')

    # ### end Alembic commands ###
