"""add face_encodings column

Revision ID: f2166171c6a5
Revises: b7704a298e1e
Create Date: 2025-10-23 09:14:02.540340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2166171c6a5'
down_revision = 'b7704a298e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encodings', sa.Text(), nullable=True))
        batch_op.drop_column('face_encoding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encoding', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('face_encodings')

    # ### end Alembic commands ###
